server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: sheeesh
  accessToken:
    lifetime: 1h
  refreshToken:
    lifetime: 1d

spring:
  main:
    allow-circular-references: true
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/login/**