server:
  port: 8000

jwt:
  secret: sheeesh
  accessToken:
    lifetime: 1h
  refreshToken:
    lifetime: 1d

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway-service
  config:
    import: "optional:config-server:http://localhost:8088"
  main:
    web-application-type=reactive:
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/user/**
#        - id: book-service
#          uri: http://localhost:8083
#          predicates:
#            - Path=/api/book/**
#        - id: wishlist-service
#          uri: http://localhost:8084
#          predicates:
#            - Path=/api/wishlist/**
#        - id: purchase-service
#          uri: http://localhost:8085
#          predicates:
#            - Path=/api/purchase/**
#        - id: review-service
#          uri: http://localhost:8086
#          predicates:
#            - Path=/api/review/**
#        - id: auth-service
#          uri: http://localhost:8087
#          predicates:
#            - Path=/login/**