server:
    port: 8085

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

management:
    tracing:
        sampling:
            probability: 1.0

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/purchase
        username: postgres
        password: 12345
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
    main:
        allow-circular-references: true
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 15MB
            enabled: true
    application:
        name: purchase-service
    config:
        import: "optional:config-server:http://localhost:8088"